version: '3.8'

services:
  backend:
    build: ./backend
    container_name: youtube-backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=35.200.244.95  # External IP of the VM running PostgreSQL
      - DB_USER=sadiq_shaikh
      - DB_PASSWORD=sadiq@123
      - DB_NAME=youtube
      - DB_PORT=5432
    networks:
      - default
