version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: youtube-backend
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
      PORT: 8080
      CLIENT_ID: ${CLIENT_ID}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend-network
    env_file:
      - ./backend/.env

volumes:
  pgdata:

networks:
  backend-network:
    driver: bridge
